name: Publish Docker image

on:
  workflow_call:
    inputs:
      registry:
        description: 'Image registry'
        default: dockerhub.com
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      tag:
        description: 'Release tag version'
        required: true
        type: string
      tag_latest:
        description: 'Tag as latest version?'
        default: true
        required: false
        type: boolean
      tag_minimal:
        default: ""
        description: 'Minimal supported tag version'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      registry:
        description: 'Image registry'
        default: dockerhub.com
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      tag:
        description: 'Release tag version'
        required: true
        type: string
      tag_latest:
        description: 'Tag as latest version?'
        default: true
        required: false
        type: boolean
      tag_minimal:
        default: ""
        description: 'Minimal supported tag version'
        required: false
        type: string

permissions:
  actions: write
  contents: write
  security-events: write

jobs:
  publish-image:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing..."

      - name: Show inputs
        run:
          echo "${{ toJSON(inputs) }}" | jq
